# Build aşaması
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app


COPY *.csproj ./
RUN dotnet restore


COPY . ./
RUN dotnet publish -c Release -o out


WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "NLayer.WebUI.dll"]
